twist_mux:
  ros__parameters:
    topics:
      joystick:
        topic   : teleop/cmd_vel
        timeout : 0.5
        priority: 100
      navigation:
        topic   : move_base/cmd_vel
        timeout : 0.5
        priority: 30
      external:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
    locks:
      estop:
        topic   : estop
        timeout : 0.0
        priority: 255